import type { Metadata } from "next";
import "./globals.css";
import Header from "./ui/header";
import { spaceGrotesk } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.className} antialiased`}>
        <div className="w-screen flex justify-center">
          <div className="md:w-3/5 ml-10 mr-10 mb-5">
            <Header/>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
